export type PrivacySection = {
  id: string;
  tocLabel: string;
  title: string;
  paragraph?: string;
  list?: { term: string; rest: string }[];
};

export const privacySections: PrivacySection[] = [
  {
    id: "information-we-collect",
    tocLabel: "Information we collect",
    title: "01. Information we collect",
    paragraph: "We collect information you give us directly and a small amount generated by your use of the platform. We deliberately keep this minimal:",
    list: [
      { term: "Account details", rest: "— name, email address and password when you sign up (or your profile from Google/Apple sign-in)." },
      { term: "Learning activity", rest: "— courses enrolled, lessons completed, quiz results and certificates earned — used to power your progress and recommendations." },
      { term: "Payment information", rest: "— processed securely by our payment partners (Stripe, PayPal). We never store full card numbers." },
      { term: "Device data", rest: "— browser type, approximate region and crash logs, used to keep the platform fast and secure." },
    ],
  },
  {
    id: "how-we-use-your-data",
    tocLabel: "How we use your data",
    title: "02. How we use your data",
    paragraph: "Every use maps to running or improving your learning experience:",
    list: [
      { term: "Deliver the service", rest: "— sync your progress across devices, issue certificates and process." },
      { term: "Personalize learning", rest: "— recommend courses and adapt AI learning paths to your pace and goals." },
      { term: "Communicate", rest: "— transactional emails, plus optional course updates and offers you can switch." },
      { term: "Protect the platform", rest: "— detect fraud, abuse and security incidents." },
    ],
  },
  {
    id: "what-we-never-do",
    tocLabel: "What we never do",
    title: "03. What we never do",
    paragraph: "Some things are off the table, permanently.",
    list: [
      { term: "No selling data", rest: "— we never sell or rent your personal information to anyone." },
      { term: "No ad tracking", rest: "— we don't share your learning history with advertisers or data brokers." },
      { term: "No reading private work", rest: "— your notes, assignments and messages are visible only to you and instructors you submit to." },
    ],
  },
  {
    id: "cookies-tracking",
    tocLabel: "Cookies & tracking",
    title: "04. Cookies & tracking",
    paragraph: "We use a small set of cookies: essential cookies to keep you signed in, preference cookies to remember settings like playback speed, and privacy-friendly analytics to understand which lessons help learners most. You can manage non-essential cookies anytime from the cookie banner or your browser settings.",
  },
  {
    id: "how-we-share",
    tocLabel: "How we share information",
    title: "05. How we share information",
    paragraph: "We share data only with service providers who help us operate — hosting (AWS), payments (Stripe, PayPal), email delivery and customer support tooling. Each partner is bound by a data-processing agreement, receives only what they need, and may not use your data for their own purposes. We may also disclose information if required by law.",
  },
  {
    id: "data-security",
    tocLabel: "Data security & retention",
    title: "06. Data security & retention",
    paragraph: "All traffic is encrypted in transit (TLS 1.3) and data is encrypted at rest (AES-256). Access is limited to staff who need it, protected by hardware security keys. We keep your data while your account is active; if you delete your account, personal data is erased within 30 days, except minimal records we're legally required to keep (like tax invoices).",
  },
  {
    id: "your-rights",
    tocLabel: "Your rights & choices",
    title: "07. Your rights & choices",
    paragraph: "Wherever you live, we extend the same rights to everyone:",
    list: [
      { term: "Access & portability", rest: "— download a copy of your data from Settings → Privacy at any time." },
      { term: "Correction & deletion", rest: "— update your profile or permanently delete your account in one click." },
      { term: "Marketing opt-out", rest: "— unsubscribe from promotional emails with one tap — transactional emails still arrive." },
      { term: "Complaint", rest: "— you may lodge a complaint with your local data-protection authority." },
    ],
  },
  {
    id: "children-updates",
    tocLabel: "Children & policy updates",
    title: "08. Children & policy updates",
    paragraph: "Edunex is not directed at children under 13 (or the minimum age in your country), and we don't knowingly collect their data. When we make meaningful changes to this policy, we'll notify you by email and in-app at least 14 days before they take effect — the version history is always available on request.",
  },
];
